spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: wisii-microservice-config-dev
---
spring:
  profiles: test
  application:
    name: wisii-microservice-config-test