spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: wisii-microservice-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/weimengdb01              # 数据库名称
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
    #控制台显示SQL
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wisii-microservice-config-dept-client8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: wisii-microservice
  company.name: www.wisii.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$